# Generated by Django 5.1.3 on 2024-12-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendor_rename_category_product_category_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('sell', 'Sell'), ('rent', 'Rent')], default='sell', max_length=5),
        ),
    ]
