# Generated by Django 5.1.3 on 2024-12-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], default='Sale', max_length=5),
        ),
    ]
