# Generated by Django 5.1.3 on 2024-12-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='custmor',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
