# Generated by Django 5.1.3 on 2024-12-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_custmor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_custmor',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
