# Generated by Django 5.1.3 on 2024-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_order_custmor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_custmor',
            name='address',
            field=models.CharField(blank=True, default='.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order_custmor',
            name='order_items',
            field=models.CharField(blank=True, default='.', max_length=200, null=True),
        ),
    ]
